#ifndef STRUCTOPOLIS_ASSETS_SCRIPTS_GAMEPLAY_CONDITIONFACTORY_H_
#define STRUCTOPOLIS_ASSETS_SCRIPTS_GAMEPLAY_CONDITIONFACTORY_H_

namespace structopolis::gameplay {

class ConditionFactory {

};

} // gameplay

#endif //STRUCTOPOLIS_ASSETS_SCRIPTS_GAMEPLAY_CONDITIONFACTORY_H_
